# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pr:
  branches:
    include:
      - master
      - 202012
  paths:
    exclude:
      - .github

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

stages:
- stage: Fake
  jobs:
  - job:
    pool:
      vmImage: ubuntu-20.04
    steps:
    - script: |
        echo exit
        exit 0
      displayName: Test
