# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


pr:
  branches:
    include:
      - multiple_checkers
  paths:
    exclude:
      - .github

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

stages:
- stage: Build
  pool: sonicbld

  jobs:
  - job: Build1
    steps:
    - script:
        echo build1
  - job: Build2
    steps:
    - script:
        echo build2
        exit 1

- stage: Test
  pool: sonicbld

  jobs:
  - job: Test1
    steps:
    - script:
        echo test1
  - job: Test2
    steps:
    - script:
        echo test2
