# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
      - 202012
  paths:
    exclude:
      - .github

pr:
  branches:
    include:
      - master
  paths:
    exclude:
      - .github

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

jobss:
- job: Build
  pool: sonicbld
  steps:
  - checkout: self
  - script: |
      git log -n 10
      git status
      git branch
      git checkout -b $(Build.SourceBranchName)
      git log -n 10
      git status
      git branch
