#!/usr/bin/env python3
"""Extract and classify real human inputs from Claude Code session records.

Backs the statistics in docs/superpowers/2026-09-03-resolute-ai-workflow-retrospective-*.md.

Usage:
    ./mine-prompts.py [PROJECT_DIR] [--out DIR]

PROJECT_DIR defaults to the resolute project's session directory:
    ~/.claude/projects/-home-sheldon-qi-sonic-buildimage/

Only top-level *.jsonl are counted as main-session records; subdirectories hold
subagent transcripts and are reported separately but excluded from the corpus.

Three filtering steps, each of which was got wrong first:

  1. Keep type=="user" records that are NOT isSidechain and have a null
     toolUseResult. Subagent turns are also persisted with role user; tool
     results likewise.
  2. Drop non-human text injected in the user role (hooks, system reminders,
     skill preambles, context-continuation summaries). Unwrap the two forms
     that WRAP real input rather than replace it:
       - "The user sent a new message while you were working:\\n<real input>"
       - <ide_selection> / <ide_opened_file> blocks
     Slash commands are kept by extracting <command-args> (the human's text).
  3. Report two dedup keys. Resuming a session re-persists earlier messages,
     so (timestamp, text) over-counts replays and text-only under-counts
     genuine repetition ("continue" typed twice).

Classification assigns each input to at most ONE category, first match wins,
and the unclassified remainder is reported. Categories are heuristics over
Chinese and English keywords; treat the magnitudes as sound and individual
numbers as approximate.
"""

import argparse
import json
import os
import re
import statistics
import sys
from collections import Counter, defaultdict

DEFAULT_PROJECT_DIR = os.path.expanduser(
    "~/.claude/projects/-home-sheldon-qi-sonic-buildimage"
)

# --- Step 2 blacklist: non-human text injected with role=user -------------
# HEAD_MARKERS are matched in the first 400 characters, because hooks sometimes
# prepend a blank line or a caveat banner. ANY_MARKERS are matched anywhere:
# skill bodies and file-change notices get appended after other content, so
# anchoring them to the head lets a 240 KB skill manual through as "input".
HEAD_MARKERS = (
    "SessionStart hook additional context:",
    "The TodoWrite tool hasn't been used recently",
    "[SYSTEM NOTIFICATION - NOT USER INPUT]",
    "Stop hook feedback:",
    "A session-scoped Stop hook is now active",
    "This session is being continued from a previous conversation",
    "<task-notification>",
    "<local-command-caveat>",
    "Plan mode is active",
    "Ultracode is",
    "# Environment",
    "# Memory",
    "Caveat: The messages below were generated by the user while running local commands",
    "Another Claude session sent a message",
    "This is the git status at the start of the conversation",
    "Based on the conversation transcript above, has the following stopping condition",
    "The task tools haven't been used recently",
    "CRITICAL: Respond with TEXT ONLY",
)
ANY_MARKERS = (
    "<system-reminder>",
    "<total_tokens>",
    "Base directory for this skill:",
    "Available agent types for the Agent tool:",
    "was modified, either by the user or by a linter",
    "The following skills are available for use with the Skill tool:",
)
INJECTED_RE = re.compile(
    r"^\s*Called the \S+ tool with the following input:", re.MULTILINE
)
# IDE preamble that WRAPS real input rather than replacing it.
IDE_PREAMBLE_RE = re.compile(
    r"^\s*The user (?:selected the lines \d+ to \d+ from|opened the file)\s+\S+[^\n]*\n?",
)
# Appended to real input by a text-only hook. Dropping the record would discard
# the human's actual words, which sit before the suffix.
SUFFIX_RE = re.compile(r"\n\s*CRITICAL: Respond with TEXT ONLY.*\Z", re.DOTALL)

MIDWORK_RE = re.compile(
    r"The user sent a new message while you were working:\s*(.*?)"
    r"(?:\s*This is how Claude Code surfaces messages|$)",
    re.DOTALL,
)
COMMAND_NAME_RE = re.compile(r"<command-name>([^<]*)</command-name>")
COMMAND_ARGS_RE = re.compile(r"<command-args>(.*?)</command-args>", re.DOTALL)
IDE_BLOCK_RE = re.compile(
    r"</?(?:ide_selection|ide_opened_file)>|<(?:ide_selection|ide_opened_file)[^>]*>",
)
INTERRUPT_RE = re.compile(r"^\s*\[Request interrupted by user[^\]]*\]\s*")

# --- Classification: first match wins ------------------------------------
CATEGORIES = [
    ("advance", r"^(继续|对|好|同意|可以|嗯|是的|ok|yes|go|go on|continue|"
                r"怎么样了|如何了|进展|好了吗|完成了吗|done\?)[。\.\!，,]*$"),
    ("option-pick", r"^\s*(先\s*[A-Da-d]\s*(再|然后)\s*[A-Da-d]|[A-Da-d]\b|选\s*[A-Da-d])"),
    ("investigate", r"调研|核实|验证|审计|深挖|查一下|查下|看一下|看下|确认|"
                    r"investigat|verify|audit|double.?check"),
    ("challenge", r"不是|不对|错了|怎么可能|说不通|不太可信|有问题|别急|"
                  r"我怀疑|存疑|你确定|重新调研|证伪"),
    ("push-commit", r"\bpush\b|提交|commit|推一版|推一次|建 ?pr|开 ?pr|合入"),
    ("minimal-diff", r"最小|回退|多余|不必要|可选的|diff|精简|简洁|删掉|去掉"),
    ("patch-style", r"\bsed\b|\bawk\b|patch|补丁|quilt|series|overlay"),
    ("orchestration", r"subagent|worktree|/goal|jsonl|cron|定时|并行|ultracode|workflow"),
    ("authorization", r"禁止|不允许|不准|允许|仅此一次|显式同意|不要动|别动|"
                      r"forbidden|allowed|do not"),
    ("clean-rebuild", r"从零|干净|清理|git clean|重建|clean.?build|reset"),
    ("doc-style", r"一段|一点一点|不要输出太多|加粗|标题|文风|太 ?ai|中英|双语|"
                  r"英文版|中文版|翻译"),
    ("review-people", r"同事|reviewer|评审|讨论|上游|社区|团队"),
]
CATEGORY_RES = [(name, re.compile(pat, re.IGNORECASE)) for name, pat in CATEGORIES]


def extract_text(content):
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        return "\n".join(
            b.get("text", "") for b in content
            if isinstance(b, dict) and b.get("type") == "text"
        )
    return ""


def normalize(text):
    """Return the human's own text, or None if the record is injected."""
    text = INTERRUPT_RE.sub("", text)
    text = SUFFIX_RE.sub("", text)

    # Unwrap mid-turn delivery before blacklisting: the wrapper contains real input.
    m = MIDWORK_RE.search(text)
    if m:
        text = m.group(1)

    # A slash command: the human's text is the arguments.
    if COMMAND_NAME_RE.search(text):
        name = COMMAND_NAME_RE.search(text).group(1).strip()
        args = COMMAND_ARGS_RE.search(text)
        args = args.group(1).strip() if args else ""
        text = f"{name} {args}".strip() if args else name

    if any(marker in text for marker in ANY_MARKERS):
        return None
    head = text[:400]
    if any(marker in head for marker in HEAD_MARKERS):
        return None
    if INJECTED_RE.search(head):
        return None

    text = IDE_BLOCK_RE.sub("", text)
    text = IDE_PREAMBLE_RE.sub("", text)
    text = text.strip()
    return text or None


def classify(text):
    for name, rx in CATEGORY_RES:
        if rx.search(text):
            return name
    return "unclassified"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("project_dir", nargs="?", default=DEFAULT_PROJECT_DIR)
    ap.add_argument("--out", default=os.path.dirname(os.path.abspath(__file__)))
    args = ap.parse_args()

    proj = os.path.expanduser(args.project_dir)
    if not os.path.isdir(proj):
        sys.exit(f"no such directory: {proj}")

    top = sorted(f for f in os.listdir(proj) if f.endswith(".jsonl"))
    # Subagent transcripts live at <session-id>/subagents/*.jsonl, one level
    # deeper than the main sessions. "memory" is a sibling directory, not a
    # session, and must not be counted.
    subdirs = sorted(
        d for d in os.listdir(proj)
        if os.path.isdir(os.path.join(proj, d)) and d != "memory"
    )
    sub_files = []
    for d in subdirs:
        for root, _, files in os.walk(os.path.join(proj, d)):
            sub_files += [
                os.path.join(root, f) for f in files if f.endswith(".jsonl")
            ]

    rows = []                      # (timestamp, file, recovered, text)
    recovered_files = set()
    sidechain_top = 0
    per_file_human = Counter()

    for fname in top:
        path = os.path.join(proj, fname)
        with open(path, encoding="utf-8", errors="replace") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    rec = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if rec.get("recovered") is True:
                    recovered_files.add(fname)
                if rec.get("type") != "user":
                    continue
                # isMeta marks harness-injected content (skill bodies, agent
                # listings) that is persisted with role=user.
                if rec.get("isMeta") is True:
                    continue
                if rec.get("isSidechain") is True:
                    sidechain_top += 1
                    continue
                if rec.get("toolUseResult") is not None:
                    continue
                text = normalize(extract_text(rec.get("message", {}).get("content")))
                if not text:
                    continue
                rows.append((rec.get("timestamp", ""), fname, fname in recovered_files, text))
                per_file_human[fname] += 1

    # Step 3: two dedup keys.
    by_ts_text, by_text = {}, {}
    for ts, fname, rec, text in rows:
        by_ts_text.setdefault((ts, text), (ts, fname, rec, text))
        by_text.setdefault(text, (ts, fname, rec, text))

    uniq = sorted(by_text.values(), key=lambda r: r[0])
    lengths = [len(r[3]) for r in uniq]
    days = {r[0][:10] for r in uniq if r[0]}

    # Native vs recovered split (a file is recovered if any record carries the flag).
    rec_rows = [r for r in uniq if r[2]]
    nat_rows = [r for r in uniq if not r[2]]

    cats = Counter(classify(r[3]) for r in uniq)

    # Advancement phrases counted with the replay-tolerant key, per the docstring.
    adv_occurrences = sum(
        1 for k in by_ts_text if classify(k[1]) in ("advance", "option-pick")
    )

    out = []
    A = out.append
    A("# Prompt corpus statistics")
    A("")
    A(f"project dir            : {proj}")
    A(f"top-level jsonl        : {len(top)}")
    A(f"  of which recovered   : {len(recovered_files)}")
    A(f"  native               : {len(top) - len(recovered_files)}")
    A(f"subagent subdirs       : {len(subdirs)} ({len(sub_files)} jsonl)")
    A(f"top-level sidechain    : {sidechain_top} user records dropped by step 1")
    A("")
    A(f"human inputs, raw            : {len(rows)}")
    A(f"human inputs, (ts,text) dedup: {len(by_ts_text)}")
    A(f"human inputs, text dedup     : {len(uniq)}")
    A(f"  from recovered files       : {len(rec_rows)}")
    A(f"  from native files          : {len(nat_rows)}")
    A(f"sessions carrying human input: {len(per_file_human)}")
    A(f"active days                  : {len(days)}")
    A(f"first / last timestamp       : {uniq[0][0]} / {uniq[-1][0]}")
    A("")
    A(f"total characters : {sum(lengths)}")
    A(f"mean / median    : {statistics.mean(lengths):.0f} / {statistics.median(lengths):.0f}")
    A(f"p90 / max        : {sorted(lengths)[int(len(lengths)*0.9)]} / {max(lengths)}")
    for bound in (10, 30, 100, 300):
        n = sum(1 for x in lengths if x <= bound)
        A(f"<= {bound:3d} chars     : {n} ({n*100//len(lengths)}%)")
    n = sum(1 for x in lengths if x >= 300)
    A(f">= 300 chars     : {n} ({n*100//len(lengths)}%)")
    A("")
    A("## Categories (mutually exclusive, first match wins, text-dedup basis)")
    A("")
    for name, _ in CATEGORIES:
        n = cats.get(name, 0)
        A(f"{name:16s} : {n:4d} ({n*100//len(uniq)}%)")
    n = cats["unclassified"]
    A(f"{'unclassified':16s} : {n:4d} ({n*100//len(uniq)}%)")
    A("")
    A(f"advance+option-pick occurrences on (ts,text) basis: {adv_occurrences}")

    report = "\n".join(out)
    print(report)

    os.makedirs(args.out, exist_ok=True)
    with open(os.path.join(args.out, "corpus-stats.txt"), "w", encoding="utf-8") as fh:
        fh.write(report + "\n")
    with open(os.path.join(args.out, "prompts-dedup.tsv"), "w", encoding="utf-8") as fh:
        fh.write("timestamp\tsource\trecovered\tcategory\ttext\n")
        for ts, fname, rec, text in uniq:
            flat = text.replace("\t", " ").replace("\n", "\\n")
            fh.write(f"{ts}\t{fname}\t{int(rec)}\t{classify(text)}\t{flat}\n")


if __name__ == "__main__":
    main()
