ifcs:
  options:
    log_level: "info"
nodes:
- node_id: "0"
  options:
    sku: "configs/sku/innovium.55200"
    netdev:
    - auto_create: "no"
      multi_interface: "yes"
    buffer_management_mode: "api_driven"
    max_lossless_tc: "2"
    skip_pll_check: "false"
    mac_clk: "750"
    sys_clk: "975"
    ifc_clk: "525"
    txring:
    - txring_id: "0"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "1"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "2"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "3"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    rxring:
    - rxring_id: "0"
      desc_count: "1024"
      prio: "1"
      queues: "0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44"
      netdev: "true"
    - rxring_id: "1"
      desc_count: "1024"
      prio: "1"
      queues: "1, 5, 9, 13, 17, 21, 25, 29, 33, 37, 41, 45"
      netdev: "true"
    - rxring_id: "2"
      desc_count: "1024"
      prio: "1"
      queues: "2, 6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46"
      netdev: "true"
    - rxring_id: "3"
      desc_count: "1024"
      prio: "1"
      queues: "3, 7, 11, 15, 19, 23, 27, 31, 35, 39, 43, 47"
      netdev: "true"
  devports:
  - id: "0"
    sysport: "1000"
    type: "cpu"
  - id: "1"
    fec: "KRFEC"
    lanes: "0:1"
    serdes_group: "14"
    speed: "25G"
    sysport: "1"
    type: "eth"
  - id: "2"
    fec: "KRFEC"
    lanes: "1:1"
    serdes_group: "14"
    speed: "25G"
    sysport: "2"
    type: "eth"
  - id: "3"
    fec: "KRFEC"
    lanes: "2:1"
    serdes_group: "14"
    speed: "25G"
    sysport: "3"
    type: "eth"
  - id: "4"
    fec: "KRFEC"
    lanes: "3:1"
    serdes_group: "14"
    speed: "25G"
    sysport: "4"
    type: "eth"
  - id: "5"
    fec: "KRFEC"
    lanes: "4:1"
    serdes_group: "14"
    speed: "25G"
    sysport: "5"
    type: "eth"
  - id: "6"
    fec: "KRFEC"
    lanes: "5:1"
    serdes_group: "14"
    speed: "25G"
    sysport: "6"
    type: "eth"
  - id: "7"
    fec: "KRFEC"
    lanes: "6:1"
    serdes_group: "14"
    speed: "25G"
    sysport: "7"
    type: "eth"
  - id: "8"
    fec: "KRFEC"
    lanes: "7:1"
    serdes_group: "14"
    speed: "25G"
    sysport: "8"
    type: "eth"
  - id: "9"
    fec: "KRFEC"
    lanes: "7:1"
    serdes_group: "13"
    speed: "25G"
    sysport: "9"
    type: "eth"
  - id: "10"
    fec: "KRFEC"
    lanes: "6:1"
    serdes_group: "13"
    speed: "25G"
    sysport: "10"
    type: "eth"
  - id: "11"
    fec: "KRFEC"
    lanes: "5:1"
    serdes_group: "13"
    speed: "25G"
    sysport: "11"
    type: "eth"
  - id: "12"
    fec: "KRFEC"
    lanes: "4:1"
    serdes_group: "13"
    speed: "25G"
    sysport: "12"
    type: "eth"
  - id: "13"
    fec: "KRFEC"
    lanes: "3:1"
    serdes_group: "13"
    speed: "25G"
    sysport: "13"
    type: "eth"
  - id: "14"
    fec: "KRFEC"
    lanes: "2:1"
    serdes_group: "13"
    speed: "25G"
    sysport: "14"
    type: "eth"
  - id: "15"
    fec: "KRFEC"
    lanes: "1:1"
    serdes_group: "13"
    speed: "25G"
    sysport: "15"
    type: "eth"
  - id: "16"
    fec: "KRFEC"
    lanes: "0:1"
    serdes_group: "13"
    speed: "25G"
    sysport: "16"
    type: "eth"
  - id: "17"
    fec: "KRFEC"
    lanes: "7:1"
    serdes_group: "11"
    speed: "25G"
    sysport: "17"
    type: "eth"
  - id: "18"
    fec: "KRFEC"
    lanes: "6:1"
    serdes_group: "11"
    speed: "25G"
    sysport: "18"
    type: "eth"
  - id: "19"
    fec: "KRFEC"
    lanes: "5:1"
    serdes_group: "11"
    speed: "25G"
    sysport: "19"
    type: "eth"
  - id: "20"
    fec: "KRFEC"
    lanes: "4:1"
    serdes_group: "11"
    speed: "25G"
    sysport: "20"
    type: "eth"
  - id: "21"
    fec: "KRFEC"
    lanes: "3:1"
    serdes_group: "11"
    speed: "25G"
    sysport: "21"
    type: "eth"
  - id: "22"
    fec: "KRFEC"
    lanes: "2:1"
    serdes_group: "11"
    speed: "25G"
    sysport: "22"
    type: "eth"
  - id: "23"
    fec: "KRFEC"
    lanes: "1:1"
    serdes_group: "11"
    speed: "25G"
    sysport: "23"
    type: "eth"
  - id: "24"
    fec: "KRFEC"
    lanes: "0:1"
    serdes_group: "11"
    speed: "25G"
    sysport: "24"
    type: "eth"
  - id: "25"
    fec: "KRFEC"
    lanes: "1:1"
    serdes_group: "5"
    speed: "25G"
    sysport: "25"
    type: "eth"
  - id: "26"
    fec: "KRFEC"
    lanes: "5:1"
    serdes_group: "5"
    speed: "25G"
    sysport: "26"
    type: "eth"
  - id: "27"
    fec: "KRFEC"
    lanes: "2:1"
    serdes_group: "5"
    speed: "25G"
    sysport: "27"
    type: "eth"
  - id: "28"
    fec: "KRFEC"
    lanes: "3:1"
    serdes_group: "5"
    speed: "25G"
    sysport: "28"
    type: "eth"
  - id: "29"
    fec: "KRFEC"
    lanes: "0:1"
    serdes_group: "5"
    speed: "25G"
    sysport: "29"
    type: "eth"
  - id: "30"
    fec: "KRFEC"
    lanes: "4:1"
    serdes_group: "5"
    speed: "25G"
    sysport: "30"
    type: "eth"
  - id: "31"
    fec: "KRFEC"
    lanes: "7:1"
    serdes_group: "5"
    speed: "25G"
    sysport: "31"
    type: "eth"
  - id: "32"
    fec: "KRFEC"
    lanes: "6:1"
    serdes_group: "5"
    speed: "25G"
    sysport: "32"
    type: "eth"
  - id: "33"
    fec: "KRFEC"
    lanes: "0:1"
    serdes_group: "3"
    speed: "25G"
    sysport: "33"
    type: "eth"
  - id: "34"
    fec: "KRFEC"
    lanes: "1:1"
    serdes_group: "3"
    speed: "25G"
    sysport: "34"
    type: "eth"
  - id: "35"
    fec: "KRFEC"
    lanes: "2:1"
    serdes_group: "3"
    speed: "25G"
    sysport: "35"
    type: "eth"
  - id: "36"
    fec: "KRFEC"
    lanes: "3:1"
    serdes_group: "3"
    speed: "25G"
    sysport: "36"
    type: "eth"
  - id: "37"
    fec: "KRFEC"
    lanes: "4:1"
    serdes_group: "3"
    speed: "25G"
    sysport: "37"
    type: "eth"
  - id: "38"
    fec: "KRFEC"
    lanes: "5:1"
    serdes_group: "3"
    speed: "25G"
    sysport: "38"
    type: "eth"
  - id: "39"
    fec: "KRFEC"
    lanes: "6:1"
    serdes_group: "3"
    speed: "25G"
    sysport: "39"
    type: "eth"
  - id: "40"
    fec: "KRFEC"
    lanes: "7:1"
    serdes_group: "3"
    speed: "25G"
    sysport: "40"
    type: "eth"
  - id: "41"
    fec: "KRFEC"
    lanes: "2:1"
    serdes_group: "2"
    speed: "25G"
    sysport: "41"
    type: "eth"
  - id: "42"
    fec: "KRFEC"
    lanes: "0:1"
    serdes_group: "2"
    speed: "25G"
    sysport: "42"
    type: "eth"
  - id: "43"
    fec: "KRFEC"
    lanes: "4:1"
    serdes_group: "2"
    speed: "25G"
    sysport: "43"
    type: "eth"
  - id: "44"
    fec: "KRFEC"
    lanes: "1:1"
    serdes_group: "2"
    speed: "25G"
    sysport: "44"
    type: "eth"
  - id: "45"
    fec: "KRFEC"
    lanes: "6:1"
    serdes_group: "2"
    speed: "25G"
    sysport: "45"
    type: "eth"
  - id: "46"
    fec: "KRFEC"
    lanes: "3:1"
    serdes_group: "2"
    speed: "25G"
    sysport: "46"
    type: "eth"
  - id: "47"
    fec: "KRFEC"
    lanes: "7:1"
    serdes_group: "2"
    speed: "25G"
    sysport: "47"
    type: "eth"
  - id: "48"
    fec: "KRFEC"
    lanes: "5:1"
    serdes_group: "2"
    speed: "25G"
    sysport: "48"
    type: "eth"
  - id: "49"
    fec: "KRFEC"
    lanes: "4:4"
    serdes_group: "9"
    speed: "100G"
    sysport: "49"
    type: "eth"
  - id: "50"
    fec: "KRFEC"
    lanes: "0:4"
    serdes_group: "9"
    speed: "100G"
    sysport: "50"
    type: "eth"
  - id: "51"
    fec: "KRFEC"
    lanes: "4:4"
    serdes_group: "8"
    speed: "100G"
    sysport: "51"
    type: "eth"
  - id: "52"
    fec: "KRFEC"
    lanes: "0:4"
    serdes_group: "8"
    speed: "100G"
    sysport: "52"
    type: "eth"
  - id: "53"
    fec: "KRFEC"
    lanes: "0:4"
    serdes_group: "1"
    speed: "100G"
    sysport: "53"
    type: "eth"
  - id: "54"
    fec: "KRFEC"
    lanes: "4:4"
    serdes_group: "1"
    speed: "100G"
    sysport: "54"
    type: "eth"
  - id: "55"
    fec: "KRFEC"
    lanes: "0:4"
    serdes_group: "0"
    speed: "100G"
    sysport: "55"
    type: "eth"
  - id: "56"
    fec: "KRFEC"
    lanes: "4:4"
    serdes_group: "0"
    speed: "100G"
    sysport: "56"
    type: "eth"
  - id: "130"
    fec: "NONE"
    lanes: "0:1"
    serdes_group: "16"
    speed: "10G"
    sysport: "130"
    type: "mgmt 0"
  - id: "131"
    fec: "NONE"
    lanes: "1:1"
    serdes_group: "16"
    speed: "10G"
    sysport: "131"
    type: "mgmt 1"
  isg:
  - id: "0"
    lane_swap: "01234567"
    rx_polarity: "00000111"
    tx_polarity: "10011110"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "1"
    lane_swap: "01234567"
    rx_polarity: "00000111"
    tx_polarity: "00010001"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "2"
    lane_swap: "01234567"
    rx_polarity: "00100000"
    tx_polarity: "01101111"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "3"
    lane_swap: "01234567"
    rx_polarity: "01000001"
    tx_polarity: "10101000"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "4"
    lane_swap: "01234567"
    rx_polarity: "00010000"
    tx_polarity: "10100000"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "5"
    lane_swap: "01234567"
    rx_polarity: "10100000"
    tx_polarity: "01100100"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "6"
    lane_swap: "01234567"
    rx_polarity: "01010000"
    tx_polarity: "00000100"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "7"
    lane_swap: "01234567"
    rx_polarity: "10000011"
    tx_polarity: "00010110"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "8"
    lane_swap: "01234567"
    rx_polarity: "00001000"
    tx_polarity: "00001000"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "9"
    lane_swap: "01234567"
    rx_polarity: "00000000"
    tx_polarity: "10100100"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "10"
    lane_swap: "01234567"
    rx_polarity: "00000000"
    tx_polarity: "00100011"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "11"
    lane_swap: "01234567"
    rx_polarity: "01000001"
    tx_polarity: "00100000"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "12"
    lane_swap: "01234567"
    rx_polarity: "00001010"
    tx_polarity: "01010111"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "13"
    lane_swap: "01234567"
    rx_polarity: "01001011"
    tx_polarity: "00111010"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "14"
    lane_swap: "01234567"
    rx_polarity: "01000000"
    tx_polarity: "11010111"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "15"
    lane_swap: "01234567"
    rx_polarity: "01000010"
    tx_polarity: "11011000"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
