ifcs:
  options:
    log_level: "info"
nodes:
- node_id: "0"
  options:
    sku: "configs/sku/innovium.55300"
    netdev:
    - auto_create: "no"
      multi_interface: "yes"
    buffer_management_mode: "api_driven"
    max_lossless_tc: "2"
    ilpm_enable: "1"
    forward_profile: "IFCS_FORWARD_PROFILE_ID_PROFILE_E"
    skip_pll_check: "false"
    mac_clk: "750"
    sys_clk: "1300"
    ifc_clk: "675"
    txring:
    - txring_id: "0"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "1"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "2"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "3"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    rxring:
    - rxring_id: "0"
      desc_count: "1024"
      prio: "1"
      queues: "0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44"
      netdev: "true"
    - rxring_id: "1"
      desc_count: "1024"
      prio: "1"
      queues: "1, 5, 9, 13, 17, 21, 25, 29, 33, 37, 41, 45"
      netdev: "true"
    - rxring_id: "2"
      desc_count: "1024"
      prio: "1"
      queues: "2, 6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46"
      netdev: "true"
    - rxring_id: "3"
      desc_count: "1024"
      prio: "1"
      queues: "3, 7, 11, 15, 19, 23, 27, 31, 35, 39, 43, 47"
      netdev: "true"
  devports:
  - id: "0"
    sysport: "129"
    type: "cpu"
  - id: "121"
    fec: "KRFEC"
    lanes: "0:4"
    serdes_group: "15"
    speed: "100G"
    sysport: "121"
    type: "eth"
  - id: "125"
    fec: "KRFEC"
    lanes: "4:4"
    serdes_group: "15"
    speed: "100G"
    sysport: "125"
    type: "eth"
  - id: "113"
    fec: "KRFEC"
    lanes: "0:4"
    serdes_group: "14"
    speed: "100G"
    sysport: "113"
    type: "eth"
  - id: "117"
    fec: "KRFEC"
    lanes: "4:4"
    serdes_group: "14"
    speed: "100G"
    sysport: "117"
    type: "eth"
  - id: "105"
    fec: "KRFEC"
    lanes: "0:4"
    serdes_group: "13"
    speed: "100G"
    sysport: "105"
    type: "eth"
  - id: "109"
    fec: "KRFEC"
    lanes: "4:4"
    serdes_group: "13"
    speed: "100G"
    sysport: "109"
    type: "eth"
  - id: "97"
    fec: "KRFEC"
    lanes: "0:4"
    serdes_group: "12"
    speed: "100G"
    sysport: "97"
    type: "eth"
  - id: "101"
    fec: "KRFEC"
    lanes: "4:4"
    serdes_group: "12"
    speed: "100G"
    sysport: "101"
    type: "eth"
  - id: "89"
    fec: "KRFEC"
    lanes: "0:4"
    serdes_group: "11"
    speed: "100G"
    sysport: "89"
    type: "eth"
  - id: "93"
    fec: "KRFEC"
    lanes: "4:4"
    serdes_group: "11"
    speed: "100G"
    sysport: "93"
    type: "eth"
  - id: "81"
    fec: "KRFEC"
    lanes: "0:4"
    serdes_group: "10"
    speed: "100G"
    sysport: "81"
    type: "eth"
  - id: "85"
    fec: "KRFEC"
    lanes: "4:4"
    serdes_group: "10"
    speed: "100G"
    sysport: "85"
    type: "eth"
  - id: "73"
    fec: "KRFEC"
    lanes: "0:4"
    serdes_group: "9"
    speed: "100G"
    sysport: "73"
    type: "eth"
  - id: "77"
    fec: "KRFEC"
    lanes: "4:4"
    serdes_group: "9"
    speed: "100G"
    sysport: "77"
    type: "eth"
  - id: "65"
    fec: "KRFEC"
    lanes: "0:4"
    serdes_group: "8"
    speed: "100G"
    sysport: "65"
    type: "eth"
  - id: "69"
    fec: "KRFEC"
    lanes: "4:4"
    serdes_group: "8"
    speed: "100G"
    sysport: "69"
    type: "eth"
  - id: "57"
    fec: "KRFEC"
    lanes: "0:4"
    serdes_group: "7"
    speed: "100G"
    sysport: "57"
    type: "eth"
  - id: "61"
    fec: "KRFEC"
    lanes: "4:4"
    serdes_group: "7"
    speed: "100G"
    sysport: "61"
    type: "eth"
  - id: "49"
    fec: "KRFEC"
    lanes: "0:4"
    serdes_group: "6"
    speed: "100G"
    sysport: "49"
    type: "eth"
  - id: "53"
    fec: "KRFEC"
    lanes: "4:4"
    serdes_group: "6"
    speed: "100G"
    sysport: "53"
    type: "eth"
  - id: "41"
    fec: "KRFEC"
    lanes: "0:4"
    serdes_group: "5"
    speed: "100G"
    sysport: "41"
    type: "eth"
  - id: "45"
    fec: "KRFEC"
    lanes: "4:4"
    serdes_group: "5"
    speed: "100G"
    sysport: "45"
    type: "eth"
  - id: "33"
    fec: "KRFEC"
    lanes: "0:4"
    serdes_group: "4"
    speed: "100G"
    sysport: "33"
    type: "eth"
  - id: "37"
    fec: "KRFEC"
    lanes: "4:4"
    serdes_group: "4"
    speed: "100G"
    sysport: "37"
    type: "eth"
  - id: "25"
    fec: "KRFEC"
    lanes: "0:4"
    serdes_group: "3"
    speed: "100G"
    sysport: "25"
    type: "eth"
  - id: "29"
    fec: "KRFEC"
    lanes: "4:4"
    serdes_group: "3"
    speed: "100G"
    sysport: "29"
    type: "eth"
  - id: "17"
    fec: "KRFEC"
    lanes: "0:4"
    serdes_group: "2"
    speed: "100G"
    sysport: "17"
    type: "eth"
  - id: "21"
    fec: "KRFEC"
    lanes: "4:4"
    serdes_group: "2"
    speed: "100G"
    sysport: "21"
    type: "eth"
  - id: "9"
    fec: "KRFEC"
    lanes: "0:4"
    serdes_group: "1"
    speed: "100G"
    sysport: "9"
    type: "eth"
  - id: "13"
    fec: "KRFEC"
    lanes: "4:4"
    serdes_group: "1"
    speed: "100G"
    sysport: "13"
    type: "eth"
  - id: "1"
    fec: "KRFEC"
    lanes: "0:4"
    serdes_group: "0"
    speed: "100G"
    sysport: "1"
    type: "eth"
  - id: "5"
    fec: "KRFEC"
    lanes: "4:4"
    serdes_group: "0"
    speed: "100G"
    sysport: "5"
    type: "eth"
#  Aux ports to be enabled later
#  - id: "33"
#    fec: "NONE"
#    lanes: "0:1"
#    serdes_group: "16"
#    speed: "10G"
#    sysport: "33"
#    type: "mgmt 0"
#  - id: "34"
#    fec: "NONE"
#    lanes: "1:1"
#    serdes_group: "16"
#    speed: "10G"
#    sysport: "34"
#    type: "mgmt 1"
  isg:
  - id: "0"
    lane_swap: "01234567"
    rx_polarity: "00000111"
    tx_polarity: "10011110"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "1"
    lane_swap: "01234567"
    rx_polarity: "00000111"
    tx_polarity: "00010001"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "2"
    lane_swap: "01234567"
    rx_polarity: "00100000"
    tx_polarity: "01101111"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "3"
    lane_swap: "01234567"
    rx_polarity: "01000001"
    tx_polarity: "10101000"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "4"
    lane_swap: "01234567"
    rx_polarity: "00010000"
    tx_polarity: "10100000"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "5"
    lane_swap: "01234567"
    rx_polarity: "10100000"
    tx_polarity: "01100100"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "6"
    lane_swap: "01234567"
    rx_polarity: "01010000"
    tx_polarity: "00000100"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "7"
    lane_swap: "01234567"
    rx_polarity: "10000011"
    tx_polarity: "00010110"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "8"
    lane_swap: "01234567"
    rx_polarity: "00001000"
    tx_polarity: "00001000"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "9"
    lane_swap: "01234567"
    rx_polarity: "00000000"
    tx_polarity: "10100100"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "10"
    lane_swap: "01234567"
    rx_polarity: "00000000"
    tx_polarity: "00100011"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "11"
    lane_swap: "01234567"
    rx_polarity: "01000001"
    tx_polarity: "00100000"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "12"
    lane_swap: "01234567"
    rx_polarity: "00001010"
    tx_polarity: "01010111"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "13"
    lane_swap: "01234567"
    rx_polarity: "01001011"
    tx_polarity: "00111010"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "14"
    lane_swap: "01234567"
    rx_polarity: "01000000"
    tx_polarity: "11010111"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
  - id: "15"
    lane_swap: "01234567"
    rx_polarity: "01000010"
    tx_polarity: "11011000"
    pre1: "-3, -3, -3, -3, -3, -3, -3, -3"
    main: "20, 20, 20, 20, 20, 20, 20, 20"
