# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
- stage: CheckOut
  pool: sonicbld
  jobs:
    - job:
      steps:
      - checkout: self
        displayName: 'checkout code'
      - bash: |
          make init
          make configure PLATFORM=broadcom
        displayName: 'make init & config'
      - template: ./template/dbg.bin.yaml
      - bash: |
          make SONIC_CONFIG_BUILD_JOBS=1 target/sonic-broadcom.bin
          make SONIC_CONFIG_BUILD_JOBS=1 target/sonic-aboot-broadcom.swi
        displayName: "make swi"
      - publish: $(Build.SourcesDirectory)/target/
        artifact: target
        displayName: "archive target"

