name: lldp
summary: SONiC lldp container
description: A Chiselled rock for SONiC lldp container
version: "1.0.0"
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core24
license: Apache-2.0

# Target architecture is amd64
platforms:
  amd64:  # Make sure this value matches your computer's architecture

environment:
  PYTHONPATH: "$SNAP/lib/python3.12/site-packages:${PYTHONPATH}"
  LD_LIBRARY_PATH: ${SNAP}/lib/:${SNAP}/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:${SNAP}/usr/lib/:${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}

layout:
  /etc/supervisor:
    bind: $SNAP_DATA/etc/supervisor
  /var/log/supervisor:
    bind: $SNAP_DATA/var/log/supervisor
  /etc/default:
    bind: $SNAP/etc/default
  /etc/rsyslog.d:
    bind: $SNAP/etc/rsyslog.d
  /etc/sysctl.d:
    bind: $SNAP/etc/sysctl.d

apps:
  lldp:
    command: usr/bin/snap-lldp-init.sh

# For meeting requirement R2, simply don't specify any entrypoint (aka "services")

parts:
  install-libyang_1.0.73_amd64:
    plugin: dump
    source-type: deb
    source: ./debs/libyang_1.0.73_amd64.deb

  install-libswsscommon_1.0.0_amd64:
    plugin: dump
    source-type: deb
    source: ./debs/libswsscommon_1.0.0_amd64.deb

  install-libyang-cpp_1.0.73_amd64:
    plugin: dump
    source-type: deb
    source: ./debs/libyang-cpp_1.0.73_amd64.deb

  install-python3-yang_1.0.73_amd64:
    plugin: dump
    source-type: deb
    source: ./debs/python3-yang_1.0.73_amd64.deb 

  install-python3-swsscommon_1.0.0_amd64:
    plugin: dump
    source-type: deb
    source: ./debs/python3-swsscommon_1.0.0_amd64.deb

  install-sonic-db-cli_1.0.0_amd64:
    plugin: dump
    source-type: deb
    source: ./debs/sonic-db-cli_1.0.0_amd64.deb

  install-sonic-eventd_1.0.0-0_amd64:
    plugin: dump
    source-type: deb
    source: ./debs/sonic-eventd_1.0.0-0_amd64.deb

  install-libsnmp40t64_5.9.4+dfsg-1.1ubuntu3_amd64:
    plugin: dump
    source-type: deb
    source: ./debs/libsnmp40t64_5.9.4+dfsg-1.1ubuntu3_amd64.deb

  install-libsnmp-base_5.9.4+dfsg-1.1ubuntu3_all:
    plugin: dump
    source-type: deb
    source: ./debs/libsnmp-base_5.9.4+dfsg-1.1ubuntu3_all.deb

  install-lldpd_1.0.16-1+deb12u1_amd64.deb:
    plugin: dump
    source-type: deb
    source: ./debs/lldpd_1.0.16-1+deb12u1_amd64.deb

  install-packages:
    plugin: nil
    stage-packages:
      - rsyslog
      # - python3
      - libpython3.12
      # docker-lldp specific packages
      - iproute2
      # package dependencies
      - libhiredis1.1.0
      - libzmq5
      - libboost-serialization1.83.0
      - libuuid1
      # lldp_syncd
      - libxml2
      # lldpd
      - libevent-2.1-7
      - libsensors5
      - libpci3
      - libperl5.38t64
      - libwrap0
      - libpcre3
      # libnl-3-200
      - libnl-3-200
      - libnl-route-3-200
      - libnl-genl-3-200
      - libnl-nf-3-200
      - libnl-cli-3-200

  install-python:
    plugin: python
    source: .
    python-packages:
      # inherited from docker-config-engine-noble
      - ./python-wheels/sonic_py_common-1.0-py3-none-any.whl
      - ./python-wheels/sonic_yang_mgmt-1.0-py3-none-any.whl
      - ./python-wheels/sonic_yang_models-1.0-py3-none-any.whl
      - ./python-wheels/sonic_containercfgd-1.0-py3-none-any.whl
      - ./python-wheels/sonic_config_engine-1.0-py3-none-any.whl
      # from docker-lldp
      - ./python-wheels/sonic_d-2.0.0-py3-none-any.whl
      - jinjanator
      - lxml
      # docker-lldp specific packages
      - click
      - supervisor==4.2.5
      - supervisord-dependent-startup==1.4.0
    stage-packages:
      - python3
      - python3-pip
      - python3-minimal
      - python3.12-minimal
      - libpython3-stdlib
      - libpython3.12-stdlib
      - libpython3.12-minimal
      - python3-venv
    organize:
      bin/supervisord: usr/local/bin/supervisord
  
  install-common-files-dump:
    plugin: dump
    source: ./snap
    source-type: local
    after: [install-packages, install-python]
    organize:
      swss_vars.j2: usr/share/sonic/templates/
      readiness_probe.sh: usr/bin/
      container_startup.py: usr/share/sonic/scripts/
      00-load-omprog.conf: etc/rsyslog.d/
      supervisord.conf: etc/supervisor/
      supervisord.conf.j2: usr/share/sonic/templates/
      critical_processes: etc/supervisor/
      supervisor-proc-exit-listener: usr/bin/
      snap-lldp-init.sh:    usr/bin/
      start.sh:               usr/bin/
      waitfor_lldp_ready.sh:  usr/bin/
      lldpd.conf.j2:          usr/share/sonic/templates/
      lldpdSysDescr.conf.j2:  usr/share/sonic/templates/
      lldpmgrd:               usr/bin/

  install-conflict-files:
    plugin: nil
    source: .
    source-type: local
    after: [install-common-files-dump]
    override-prime: |
      mkdir -p var/log/supervisor
      mkdir -p etc/supervisor/conf.d
      mkdir -p etc/default/
      cp ${CRAFT_PROJECT_DIR}/snap/rsyslog.conf   etc/
      cp ${CRAFT_PROJECT_DIR}/snap/lldpd   etc/default/
