ifcs:
  options:
    log_level: "off"
nodes:
- node_id: "0"
  options:
    sku: "configs/sku/innovium.77700_A"
    netdev:
    - auto_create: "no"
      multi_interface: "yes"
    buffer_management_mode: "api_driven"
    max_lossless_tc: "2"
    skip_pll_check: "false"
    mbist_on_init: "true"
    ilpm_enable: "1"
    forward_profile: "IFCS_FORWARD_PROFILE_ID_PROFILE_E"
    txring:
    - txring_id: "0"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "1"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "2"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    - txring_id: "3"
      desc_count: "1024"
      prio: "1"
      netdev: "true"
    rxring:
    - rxring_id: "0"                                         
      desc_count: "1024"                                     
      prio: "1"     
      netdev: "true"      
      queues: "0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39"  
    - rxring_id: "1"                                         
      desc_count: "1024"                                     
      prio: "1"    
      netdev: "true"      
      queues: "1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40"  
    - rxring_id: "2"                                         
      desc_count: "1024"                                     
      prio: "1"
      netdev: "true"      
      queues: "2, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 47" 
    - rxring_id: "3"                                         
      desc_count: "1024"                                     
      prio: "1"     
      queues: "42, 43, 44, 45, 46" 
    sys_clk: "1720"
    ifc_clk: "1200"
    mac_clk: "1340"
  devports:
  - id: "0"
    sysport: "1000"
    type: "cpu"
  - fec: "KPFEC"
    id: "1"
    lanes: "0:8"
    serdes_group: "4"
    speed: "400G"
    sysport: "1"
    type: "eth"
  - fec: "KPFEC"
    id: "9"
    lanes: "0:8"
    serdes_group: "5"
    speed: "400G"
    sysport: "9"
    type: "eth"
  - fec: "KPFEC"
    id: "17"
    lanes: "0:8"
    serdes_group: "6"
    speed: "400G"
    sysport: "17"
    type: "eth"
  - fec: "KPFEC"
    id: "25"
    lanes: "0:8"
    serdes_group: "7"
    speed: "400G"
    sysport: "25"
    type: "eth"
  - fec: "KPFEC"
    id: "33"
    lanes: "0:8"
    serdes_group: "0"
    speed: "400G"
    sysport: "33"
    type: "eth"
  - fec: "KPFEC"
    id: "41"
    lanes: "0:8"
    serdes_group: "1"
    speed: "400G"
    sysport: "41"
    type: "eth"
  - fec: "KPFEC"
    id: "49"
    lanes: "0:8"
    serdes_group: "2"
    speed: "400G"
    sysport: "49"
    type: "eth"
  - fec: "KPFEC"
    id: "57"
    lanes: "0:8"
    serdes_group: "3"
    speed: "400G"
    sysport: "57"
    type: "eth"
  - fec: "KPFEC"
    id: "65"
    lanes: "0:8"
    serdes_group: "28"
    speed: "400G"
    sysport: "65"
    type: "eth"
  - fec: "KPFEC"
    id: "73"
    lanes: "0:8"
    serdes_group: "29"
    speed: "400G"
    sysport: "73"
    type: "eth"
  - fec: "KPFEC"
    id: "81"
    lanes: "0:8"
    serdes_group: "30"
    speed: "400G"
    sysport: "81"
    type: "eth"
  - fec: "KPFEC"
    id: "89"
    lanes: "0:8"
    serdes_group: "31"
    speed: "400G"
    sysport: "89"
    type: "eth"
  - fec: "KPFEC"
    id: "97"
    lanes: "0:8"
    serdes_group: "24"
    speed: "400G"
    sysport: "97"
    type: "eth"
  - fec: "KPFEC"
    id: "105"
    lanes: "0:8"
    serdes_group: "25"
    speed: "400G"
    sysport: "105"
    type: "eth"
  - fec: "KPFEC"
    id: "113"
    lanes: "0:8"
    serdes_group: "26"
    speed: "400G"
    sysport: "113"
    type: "eth"
  - fec: "KPFEC"
    id: "121"
    lanes: "0:8"
    serdes_group: "27"
    speed: "400G"
    sysport: "121"
    type: "eth"
  - fec: "KPFEC"
    id: "129"
    lanes: "0:8"
    serdes_group: "20"
    speed: "400G"
    sysport: "129"
    type: "eth"
  - fec: "KPFEC"
    id: "137"
    lanes: "0:8"
    serdes_group: "21"
    speed: "400G"
    sysport: "137"
    type: "eth"
  - fec: "KPFEC"
    id: "145"
    lanes: "0:8"
    serdes_group: "22"
    speed: "400G"
    sysport: "145"
    type: "eth"
  - fec: "KPFEC"
    id: "153"
    lanes: "0:8"
    serdes_group: "23"
    speed: "400G"
    sysport: "153"
    type: "eth"
  - fec: "KPFEC"
    id: "161"
    lanes: "0:8"
    serdes_group: "16"
    speed: "400G"
    sysport: "161"
    type: "eth"
  - fec: "KPFEC"
    id: "169"
    lanes: "0:8"
    serdes_group: "17"
    speed: "400G"
    sysport: "169"
    type: "eth"
  - fec: "KPFEC"
    id: "177"
    lanes: "0:8"
    serdes_group: "18"
    speed: "400G"
    sysport: "177"
    type: "eth"
  - fec: "KPFEC"
    id: "185"
    lanes: "0:8"
    serdes_group: "19"
    speed: "400G"
    sysport: "185"
    type: "eth"
  - fec: "KPFEC"
    id: "193"
    lanes: "0:8"
    serdes_group: "12"
    speed: "400G"
    sysport: "193"
    type: "eth"
  - fec: "KPFEC"
    id: "201"
    lanes: "0:8"
    serdes_group: "13"
    speed: "400G"
    sysport: "201"
    type: "eth"
  - fec: "KPFEC"
    id: "209"
    lanes: "0:8"
    serdes_group: "14"
    speed: "400G"
    sysport: "209"
    type: "eth"
  - fec: "KPFEC"
    id: "217"
    lanes: "0:8"
    serdes_group: "15"
    speed: "400G"
    sysport: "217"
    type: "eth"
  - fec: "KPFEC"
    id: "225"
    lanes: "0:8"
    serdes_group: "8"
    speed: "400G"
    sysport: "225"
    type: "eth"
  - fec: "KPFEC"
    id: "233"
    lanes: "0:8"
    serdes_group: "9"
    speed: "400G"
    sysport: "233"
    type: "eth"
  - fec: "KPFEC"
    id: "241"
    lanes: "0:8"
    serdes_group: "10"
    speed: "400G"
    sysport: "241"
    type: "eth"
  - fec: "KPFEC"
    id: "249"
    lanes: "0:8"
    serdes_group: "11"
    speed: "400G"
    sysport: "249"
    type: "eth"
  isg:
  - id: "0"
    tx_polarity: "01011011"
    rx_polarity: "11001111"
    lane_swap: "01235467"
  - id: "1"
    tx_polarity: "01011011"
    rx_polarity: "01001111"
    lane_swap: "01234567"
  - id: "2"
    tx_polarity: "10110100"
    rx_polarity: "10001110"
    lane_swap: "73215460"
  - id: "3"
    tx_polarity: "11111110"
    rx_polarity: "10011111"
    lane_swap: "71234560"
  - id: "4"
    tx_polarity: "01001011"
    rx_polarity: "11011010"
    lane_swap: "01235467"
  - id: "5"
    tx_polarity: "01001011"
    rx_polarity: "01001111"
    lane_swap: "01234567"
  - id: "6"
    tx_polarity: "11110100"
    rx_polarity: "10010110"
    lane_swap: "73215460"
  - id: "7"
    tx_polarity: "11111101"
    rx_polarity: "11110011"
    lane_swap: "53164720"
  - id: "8"
    tx_polarity: "00101001"
    rx_polarity: "01101001"
    lane_swap: "01234567"
  - id: "9"
    tx_polarity: "00101001"
    rx_polarity: "01101001"
    lane_swap: "01234567"
  - id: "10"
    tx_polarity: "10010110"
    rx_polarity: "10110100"
    lane_swap: "73215460"
  - id: "11"
    tx_polarity: "10000100"
    rx_polarity: "00010100"
    lane_swap: "71635420"
  - id: "12"
    tx_polarity: "00101001"
    rx_polarity: "10001001"
    lane_swap: "01234567"
  - id: "13"
    tx_polarity: "01101001"
    rx_polarity: "00001011"
    lane_swap: "01235467"
  - id: "14"
    tx_polarity: "10000110"
    rx_polarity: "10000010"
    lane_swap: "73215460"
  - id: "15"
    tx_polarity: "10000100"
    rx_polarity: "10010100"
    lane_swap: "73615420"
  - id: "16"
    tx_polarity: "00101001"
    rx_polarity: "00001011"
    lane_swap: "01234567"
  - id: "17"
    tx_polarity: "00101001"
    rx_polarity: "00001011"
    lane_swap: "01235467"
  - id: "18"
    tx_polarity: "00010110"
    rx_polarity: "10010110"
    lane_swap: "73215460"
  - id: "19"
    tx_polarity: "11101110"
    rx_polarity: "10100100"
    lane_swap: "73615420"
  - id: "20"
    tx_polarity: "01001101"
    rx_polarity: "11101011"
    lane_swap: "01234567"
  - id: "21"
    tx_polarity: "11011011"
    rx_polarity: "10001011"
    lane_swap: "01234567"
  - id: "22"
    tx_polarity: "11110100"
    rx_polarity: "10001111"
    lane_swap: "73215460"
  - id: "23"
    tx_polarity: "11110110"
    rx_polarity: "01011100"
    lane_swap: "73615420"
  - id: "24"
    tx_polarity: "01011011"
    rx_polarity: "01101101"
    lane_swap: "01234567"
  - id: "25"
    tx_polarity: "01001011"
    rx_polarity: "01101101"
    lane_swap: "01234567"
  - id: "26"
    tx_polarity: "11110100"
    rx_polarity: "10111100"
    lane_swap: "73215460"
  - id: "27"
    tx_polarity: "10111100"
    rx_polarity: "00010100"
    lane_swap: "73615420"
  - id: "28"
    tx_polarity: "01001011"
    rx_polarity: "01010101"
    lane_swap: "01235467"
  - id: "29"
    tx_polarity: "01011011"
    rx_polarity: "11001010"
    lane_swap: "01234567"
  - id: "30"
    tx_polarity: "11110100"
    rx_polarity: "00010111"
    lane_swap: "73215460"
  - id: "31"
    tx_polarity: "11110100"
    rx_polarity: "00110111"
    lane_swap: "73615420"
  - id: "32"
    tx_polarity: "00000000"
    rx_polarity: "00000000"
    lane_swap: "01234567"
