# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
- cron: "0 8 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master

trigger: none
pr: none

variables:
- group: Container-Registry

resources:
  repositories:
  - repository: sonic-build-tools
    type: github
    endpoint: build
    name: Azure/sonic-build-tools

stages:
- stage: Build
  jobs:
  - job: Build
    pool: sonicbld
    timeoutInMinutes: 360
    steps:
    - template: ../cleanup.yml
    - checkout: self
      clean: true
      #submodules: recursive
    - checkout: sonic-build-tools
    - script: |
        set -xe
        pwd
        find . -maxdepth 3
        echo $WorkSpace
        echo $REGISTRY_USERNAME
        echo $REGISTRY_PASSWD
        cd sonic-buildimage
        make configure PLATFORM=generic
        make target/docker-sonic-mgmt.gz
      displayName: Build docker-sonic-mgmt.gz
      env:
        WorkSpace: $(Agent.BuildDirectory)
        REGISTRY_USERNAME: $(sonicdev-user)
        REGISTRY_PASSWD: $(sonicdev-password)
    - script: |
        set -xe
        $(Agent.BuildDirectory)/sonic-build-tools/script/lib/docker-upload.sh
      displayName: Upload docker
      env:
        DOCKER_IMAGE_FILE: 'docker-sonic-mgmt.gz'
        DOCKER_IMAGE_TAG: 'latest'
        DOCKER_IMAGE_FILE_DIR: 'sonic-buildimage/target'
        BUILD_NUMBER: $(Build.BuildNumber)
        REGISTRY_USERNAME: $(sonicdev-user)
        REGISTRY_PASSWD: $(sonicdev-password)
        REGISTRY_SERVER: 'sonicdev-microsoft.azurecr.io'
        REGISTRY_PORT: 443