name: database
summary: SONiC database container
description: A Chiselled rock for SONiC database container
version: "1.0.0"

# Use a "bare" base for an even smaller rock
base: core24 

license: Apache-2.0
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
layout:
  /etc/supervisor.conf.d:
    bind: $SNAP_DATA/etc/supervisor/conf.d
  /etc/supervisor.critical_processes:
    bind-file: $SNAP_DATA/etc/supervisor/critical_processes
  /etc/supervisor:
    bind: $SNAP/etc/supervisor
  /var/log/supervisor:
    bind: $SNAP_DATA/var/log/supervisor
  /var/lib/database:
    bind: $SNAP_DATA/var/lib/database
  /var/lib/redis:
    bind: $SNAP_DATA/var/lib/redis
  /etc/redis:
    bind: $SNAP/etc/redis

# Target architecture is amd64
platforms:
  amd64:  # Make sure this value matches your computer's architecture

environment:
  PYTHONPATH: "$SNAP/lib/python3.12/site-packages:${PYTHONPATH}"
  PATH: $SNAP/usr/bin:$SNAP/bin:$SNAP/usr/sbin:$SNAP/sbin:${SNAP}/usr/local/bin/:$PATH
  LD_LIBRARY_PATH: ${SNAP}/lib/:${SNAP}/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:${SNAP}/usr/lib/:${SNAP}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}


apps:
  database:
    command: bin/snap-database-init.sh
    # daemon: simple
    plugs:
      - network
      - network-bind

parts:
  install-libyang_1.0.73_amd64:
    plugin: dump
    source-type: deb
    source: ./debs/libyang_1.0.73_amd64.deb

  install-libswsscommon_1.0.0_amd64:
    plugin: dump
    source-type: deb
    source: ./debs/libswsscommon_1.0.0_amd64.deb

  install-libyang-cpp_1.0.73_amd64:
    plugin: dump
    source-type: deb
    source: ./debs/libyang-cpp_1.0.73_amd64.deb

  install-python3-yang_1.0.73_amd64:
    plugin: dump
    source-type: deb
    source: ./debs/python3-yang_1.0.73_amd64.deb 

  install-python3-swsscommon_1.0.0_amd64:
    plugin: dump
    source-type: deb
    source: ./debs/python3-swsscommon_1.0.0_amd64.deb

  install-sonic-db-cli_1.0.0_amd64:
    plugin: dump
    source-type: deb
    source: ./debs/sonic-db-cli_1.0.0_amd64.deb

  install-sonic-eventd_1.0.0-0_amd64:
    plugin: dump
    source-type: deb
    source: ./debs/sonic-eventd_1.0.0-0_amd64.deb

  install-libdashapi_1.0.0_amd64:
    plugin: dump
    source-type: deb
    source: ./debs/libdashapi_1.0.0_amd64.deb

  install-packages:
    plugin: nil
    stage-packages:
      - rsyslog
      - python3
      - libpython3.12
      # docker-database specific packages
      - redis-tools
      - redis-server
      - iproute2
      # package dependencies
      - libhiredis1.1.0
      - libzmq5
      - libboost-serialization1.83.0
      - libuuid1
      - libpcre3
      # libnl-3-200
      - libnl-3-200
      - libnl-route-3-200
      - libnl-genl-3-200
      - libnl-nf-3-200
      - libnl-cli-3-200

  install-python:
    plugin: python
    source: .
    python-packages:
      # common - inherited from docker-config-engine
      - ./python-wheels/sonic_py_common-1.0-py3-none-any.whl
      - ./python-wheels/sonic_yang_mgmt-1.0-py3-none-any.whl
      - ./python-wheels/sonic_yang_models-1.0-py3-none-any.whl
      - ./python-wheels/sonic_containercfgd-1.0-py3-none-any.whl
      - ./python-wheels/sonic_config_engine-1.0-py3-none-any.whl
      - jinjanator
      # docker-database specific packages
      - click
      - supervisor==4.2.5
      - supervisord-dependent-startup==1.4.0
      - lxml
    stage-packages:
      - python3
      - python3-pip
      - python3-minimal
      - python3.12-minimal
      - libpython3-stdlib
      - libpython3.12-stdlib
      - libpython3.12-minimal
      - python3-venv

  install-common-files-dump:
    plugin: dump
    source: ./snap
    source-type: local
    after: [install-packages, install-python]
    organize:
      swss_vars.j2: usr/share/sonic/templates/
      readiness_probe.sh: usr/bin/
      container_startup.py: usr/share/sonic/scripts/
      00-load-omprog.conf: etc/rsyslog.d/
      supervisord.conf: etc/supervisor/
      supervisord.conf.j2: usr/share/sonic/templates/
      critical_processes.j2: usr/share/sonic/templates/
      sysctl-net.conf: etc/sysctl.d/
      supervisor-proc-exit-listener: usr/bin/
      snap-database-init.sh: bin/
      flush_unused_database: usr/local/bin/
      update_chassisdb_config: usr/local/bin/
      database_config.json.j2: usr/share/sonic/templates/
      database_global.json.j2: usr/share/sonic/templates/

  install-conflict-files:
    plugin: nil
    source: .
    source-type: local
    after: [install-common-files-dump]
    override-prime: |
      mkdir -p var/log/supervisor
      mkdir -p etc/supervisor/conf.d
      mkdir -p etc/redis/
      cp ${CRAFT_PROJECT_DIR}/snap/redis.conf     etc/redis/
      cp ${CRAFT_PROJECT_DIR}/snap/rsyslog.conf   etc/
