# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
- cron: "0 8 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true

trigger: none
pr: none

jobs:
- template: ../build-template.yml
  parameters:
    platform: centec
    platform_short: centec
    cache_mode: wcache
    dbg_image: true
    sync_rpc_image: true
    reproducible_options: "SONIC_VERSION_CONTROL_COMPONENTS=deb,py2,py3,web"
    postSteps: |
    - script:
        make freeze
        git status files/build/versions
        git add files/build/versions
        git diff HEAD files/build/versions
      displayName: "Show git diff"
