# The azure pipeline template for Official build, and upgrade version build

parameters:
- name: 'jobFilters'
  type: object
  default: ''
- name: 'buildOptions'
  type: string
  default: 'SONIC_CONFIG_BUILD_JOBS=1'
- name: 'preSteps'
  type: stepList
  default: []
- name: 'postSteps'
  type: stepList
  default: []
- name: 'jobGroups'
  type: object
  default: ''
- name: 'qemuOrCrossBuild'
  type: boolean
  default: false

jobs:
- template: azure-pipelines-image-template.yml
  parameters:
    jobFilters: ${{ parameters.jobFilters }}
    preSteps: ${{ parameters.preSteps }}
    postSteps: ${{ parameters.postSteps }}
    jobVariables:
      PLATFORM_AZP: $(GROUP_NAME)
      PLATFORM_ARCH: amd64
      BUILD_NUMBER: $(Build.BuildId)
      BUILD_OPTIONS: ${{ parameters.buildOptions }}
      DOCKER_DATA_ROOT_FOR_MULTIARCH: /data/march/docker
      dbg_image: no
      asan_image: no
      swi_image: no
      docker_syncd_rpc_image: no
      syncd_rpc_image: no
      platform_rpc: no
      ${{ if parameters.qemuOrCrossBuild }}:
        SONIC_SLAVE_DOCKER_DRIVER: 'vfs'
        CACHE_MODE: 'none'
    ${{ if ne(parameters.jobGroups, '') }}:
      jobGroups: ${{ parameters.jobGroups }}
    ${{ if eq(parameters.jobGroups, '') }}:
      jobGroups:
        - name: vs
          variables:
            dbg_image: yes
            asan_image: yes

        - name: barefoot
          variables:
            docker_syncd_rpc_image: yes
            platform_rpc: bfn
            swi_image: yes

        - name: broadcom
          timeoutInMinutes: 1440
          variables:
            dbg_image: yes
            swi_image: yes
            docker_syncd_rpc_image: yes
            platform_rpc: brcm

        - name: centec
          variables:
            dbg_image: yes
            docker_syncd_rpc_image: yes
            platform_rpc: centec

        - name: centec-arm64
          ${{ if not(parameters.qemuOrCrossBuild) }}:
            pool: sonicbld-arm64
          timeoutInMinutes: 2880
          variables:
            PLATFORM_ARCH: arm64

        - name: generic
          variables:
            dbg_image: yes

        - name: innovium
          variables:
            dbg_image: yes

        - name: marvell-armhf
          ${{ if not(parameters.qemuOrCrossBuild) }}:
            pool: sonicbld-armhf
          timeoutInMinutes: 2880
          variables:
            PLATFORM_ARCH: armhf

        - name: marvell-arm64
          ${{ if not(parameters.qemuOrCrossBuild) }}:
            pool: sonicbld-arm64
          timeoutInMinutes: 2880
          variables:
            PLATFORM_ARCH: arm64

        - name: pensando
          pool: sonicbld-arm64
          variables:
            PLATFORM_ARCH: arm64

        - name: marvell

        - name: mellanox
          variables:
            dbg_image: yes
            docker_syncd_rpc_image: yes
            syncd_rpc_image: yes
            platform_rpc: mlnx

        - name: nephos
          variables:
            dbg_image: yes
            docker_syncd_rpc_image: yes
            platform_rpc: nephos

    buildSteps:
      - template: .azure-pipelines/template-skipvstest.yml@buildimage
      - template: .azure-pipelines/template-daemon.yml@buildimage
      - bash: |
          set -ex
          make $BUILD_OPTIONS target/sonic-pensando.tar NOBUSTER=0 NOBULLSEYE=0
        displayName: "Build sonic image"
      - template: .azure-pipelines/check-dirty-version.yml@buildimage
