# The azure pipeline template for Official build, and upgrade version build

parameters:
- name: 'jobFilters'
  type: object
  default: ''
- name: 'buildOptions'
  type: string
  default: 'SONIC_CONFIG_BUILD_JOBS=1'
- name: 'preSteps'
  type: stepList
  default: []
- name: 'postSteps'
  type: stepList
  default: []

jobs:
- template: azure-pipelines-job-groups.yml
  parameters:
    jobFilters: ${{ parameters.jobFilters }}
    buildOptions: ${{ parameters.buildOptions }}
    preSteps: ${{ parameters.preSteps }}
    postSteps: ${{ parameters.postSteps }}
    jobGroups:
      - name: vs
        script: |
          make $(BUILD_OPTIONS) INSTALL_DEBUG_TOOLS=y target/sonic-vs.img.gz
          mv target/sonic-vs.img.gz target/sonic-vs-dbg.img.gz
          make $(BUILD_OPTIONS) target/docker-sonic-vs.gz target/sonic-vs.img.gz target/docker-ptf.gz
      - name: broadcom
        script: |
          make $(BUILD_OPTIONS) INSTALL_DEBUG_TOOLS=y target/sonic-broadcom.bin
          mv target/sonic-broadcom.bin target/sonic-broadcom-dbg.bin
          make $(BUILD_OPTIONS) target/sonic-broadcom.bin 
          make $(BUILD_OPTIONS) ENABLE_IMAGE_SIGNATURE=y target/sonic-aboot-broadcom.swi
          make $(BUILD_OPTIONS) target/sonic-broadcom.raw
          make $(BUILD_OPTIONS) ENABLE_SYNCD_RPC=y target/docker-syncd-brcm-rpc.gz
      - name: mellanox
        script: |
          make $(BUILD_OPTIONS) INSTALL_DEBUG_TOOLS=y target/sonic-mellanox.bin
          mv target/sonic-mellanox.bin target/sonic-mellanox-dbg.bin
          make $(BUILD_OPTIONS) ENABLE_SYNCD_RPC=y target/sonic-aboot-mlnx-rpc.gz
      - name: barefoot
        script: |
          make $(BUILD_OPTIONS) target/sonic-barefoot.bin
          make $(BUILD_OPTIONS) ENABLE_IMAGE_SIGNATURE=y target/sonic-aboot-barefoot.swi
      - name: generic
        script: |
          make $(BUILD_OPTIONS) INSTALL_DEBUG_TOOLS=y target/sonic-generic.bin
          mv target/sonic-generic.bin target/sonic-generic-dbg.bin
          make $(BUILD_OPTIONS) target/sonic-generic.bin
      - name: innovium
        script: |
          make $(BUILD_OPTIONS) ENABLE_IMAGE_SIGNATURE=y target/sonic-aboot-innovium.swi
          make $(BUILD_OPTIONS) target/sonic-innovium.bin
      - name: nephos
        script: |
          make $(BUILD_OPTIONS) INSTALL_DEBUG_TOOLS=y target/sonic-nephos.bin
          mv target/sonic-nephos.bin target/sonic-nephos-dbg.bin
          make $(BUILD_OPTIONS) ENABLE_SYNCD_RPC=y target/docker-syncd-nephos-rpc.gz
          make $(BUILD_OPTIONS) target/sonic-nephos.bin
      - name: marvell-armhf
        pool: sonicbld_8c
        timeoutInMinutes: 3600
        variables:
          PLATFORM_ARCH: armhf
        script: |
          make $(BUILD_OPTIONS) target/sonic-marvell-armhf.bin
      - name: centec
        script: |
          make $(BUILD_OPTIONS) INSTALL_DEBUG_TOOLS=y target/sonic-centec.bin
          mv target/sonic-centec.bin target/sonic-centec-dbg.bin
          make $(BUILD_OPTIONS) target/sonic-centec.bin
          make $(BUILD_OPTIONS) ENABLE_IMAGE_SIGNATURE=y target/sonic-aboot-centec.swi
      - name: centec-arm64
        pool: sonicbld_8c
        timeoutInMinutes: 3600
        variables:
          PLATFORM_ARCH: arm64
        script: |
          make $(BUILD_OPTIONS) target/sonic-centec-arm64.bin
          make $(BUILD_OPTIONS) ENABLE_SYNCD_RPC=y target/docker-syncd-centec-arm64-rpc.gz
