# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

schedules:
- cron: "0 0 * * *"
  displayName: Daily Build
  branches:
    include:
    - 20*
    exclude:
    - 200*
    - 201*
    - 202006
  always: true

resources:
  repositories:
  - repository: buildimage
    type: github
    name: Azure/sonic-buildimage
    ref: master
    endpoint: build

pool: sonicbld

parameters:
- name: 'jobFilters'
  type: object
  default:
  - vs
  - barefoot
  - broadcom
  - centec
  - centec-arm64
  - generic
  - marvell-armhf
  - mellanox

stages:
- stage: Build
  variables:
    - name: CACHE_MODE
      value: none
    - name: VERSION_CONTROL_OPTIONS
      value: 'SONIC_VERSION_CONTROL_COMPONENTS='
    - template: .azure-pipelines/template-variables.yml@buildimage
  jobs:
  - template: azure-pipelines-build.yml
    parameters:
      jobFilters: ${{ parameters.jobFilters }}
      buildOptions: '${{ variables.VERSION_CONTROL_OPTIONS }} ENABLE_DOCKER_BASE_PULL=n SONIC_BUILD_JOBS=$(nproc) ENABLE_IMAGE_SIGNATURE=y'
      preSteps:
      - template: .azure-pipelines/template-clean-sonic-slave.yml@buildimage
- stage: UpgradeVersions
  jobs:
  - template: template-gen-version.yml
