pr: none
trigger: none
schedules:
- cron: "15 7 * * *"
  displayName: Daily build
  branches:
    include:
    - master
    - refs/heads/202???
resources:
  repositories:
  - repository: buildimage
    type: github
    name: liushilongbuaa/sonic-buildimage
    ref: master
    endpoint: liushilongbuaa

pool: sonicbld

jobs:
- job: Build
  timeoutInMinutes: 120
  steps:
  - template: .azure-pipelines/template-commonlib.yml@buildimage
