pr: none
trigger: none
schedules:
- cron: "0 0 * * *"
  displayName: Daily build
  branches:
    include:
      - master
      - 202???
resources:
  repositories:
  - repository: buildimage
    type: github
    name: Azure/sonic-buildimage
    ref: master
    endpoint: build

pool: sonicbld

jobs:
- job: Build
  timeoutInMinutes: 120
  steps:
  - template: .azure-pipelines/template-commonlib.yml@buildimage
