steps:
- script: |
    sudo kill -9 `sudo cat /var/run/march/docker.pid` || true
    sudo rm -f /var/run/march/docker.pid || true
    sudo rm -rf fsroot || true
    git clean -xfdf
    git reset --hard
    git submodule foreach --recursive 'git clean -xfdf || true'
    git submodule foreach --recursive 'git reset --hard || true'
    git submodule foreach --recursive 'git remote update || true'
    git submodule update --init --recursive
  displayName: "Clean Workspace"
