steps:
- script: |
    sudo kill -9 `sudo cat /var/run/march/docker.pid` || true
    sudo rm -f /var/run/march/docker.pid || true
    sudo rm -rf sonic-buildimage || sudo rm -rf ../sonic-buildimage || true
  displayName: "Clean Workspace"