pr: none
trigger: none
schedules:
- cron: "0 0 * * *"
  displayName: Daily build
  branches:
    include:
    - master
    - 202???
resources:
- repository: buildimage
  type: github
  name: liushilongbuaa/sonic-buildimage
  ref: build-common-pkg
  endpoint: liushilongbuaa

jobs:
- template: .azure-pipelines/template-commonlib.yml@buildimage
