# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
# Clean up the cache $(keep_days) days ago

schedules:
- cron: "0 0 * * *"
  branches:
    include:
    - master
  always: true

trigger: none
pr: none

jobs:
- job: Build
  pool: sonicbld
  timeoutInMinutes: 5
  steps:
  - checkout: none
  - script: |
      set -xe
      sudo find /nfs/dpkg_cache/ -name *.tgz -mtime +$(keep_days) -type f -delete
    displayName: clean dpkg cache
    
