# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
- cron: "0 8 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true

trigger: none
pr: none

variables:
  JOB_NAME: build

stages:
- stage: Build
  jobs:
  - template: build-template.yml
    parameters:
      platform:  $[ variables['platform'] ]
      platform_short: $(platform)
      cache_mode: wcache
      timeout: $[ variables['TIMEOUTINMINUTES'] ]
      dbg_image: false
      swi_image: false
      raw_image: false
      sync_rpc_image: $(sync_rpc_image)

