# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
- cron: "0 */6 * * *"
  displayName: Build cache quickly
  branches:
    include:
    - master

trigger: none
pr: none

parameters:
- name: 'jobFilters'
  type: object
  default: ''
- name: 'buildOptions'
  type: string
  default: 'SONIC_CONFIG_BUILD_JOBS=8'
- name: 'buildOptions'
  type: string
  default: 'SONIC_CONFIG_MAKE_JOBS=16'
- name: 'buildOptions'
  type: string
  default: 'SONIC_DPKG_CACHE_METHOD=cache'
- name: 'preSteps'
  type: stepList
  default: []
- name: 'postSteps'
  type: stepList
  default: []
- name: 'jobGroups'
  type: object
  default: ''
- name: 'qemuOrCrossBuild'
  type: boolean
  default: false

stages:
- stage: Build
  pool: sonicbld
  variables:
  - name: CACHE_MODE
    value: cache
  - template: azure-pipelines-repd-build-variables.yml
  jobs:
  - template: azure-pipelines-build.yml
    parameters:
      buildOptions: 'USERNAME=admin SONIC_BUILD_JOBS=$(nproc)'
      jobGroups:
        - name: centec-arm64
          pool: sonicbld-arm64
            timeoutInMinutes: 1200
            variables:
              PLATFORM_ARCH: arm64
