trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master

stages:
- stage: Build
  jobs:
  - job:
    pool: sonicbld
    displayName: "build"
    timeoutInMinutes: 60
    steps:
    - checkout: self
      clean: true
      submodules: recursive
      displayName: 'Checkout code'
    - script: |
        echo Hello
        # the following is copied from jenkins
        # set -ex
        # python2 setup.py bdist_wheel
        # python3 setup.py bdist_wheel
        # mkdir -p target/python-wheels/
        # cp dist/swsssdk-2.0.1-{py2,py3}-none-any.whl target/python-wheels/
    - publish: $(System.DefaultWorkingDirectory)/target/python-wheels/
      artifact: sonic-py-swsssdk
      displayName: "Archive sonic image"
