schedules:
- cron: "0 0 * * *"
  branches:
    include:
    - master
    - 202???
  always: true
trigger: none
pr: none

resources:
 repositories:
  - repository: buildimage
    type: github
    name: Azure/sonic-buildimage
    ref: master
    endpoint: build
     
jobs:
- template: .azure-pipelines/template-syncdockerimage.yml@buildimage
