steps:
- ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
  - script: |
      set -ex
      git config --global user.email "test@example.com"
      git config --global user.name "CI agent"
      tar_branch=origin/$(System.PullRequest.TargetBranch)
      git rebase $tar_branch
      git diff $tar_branch --name-only | grep -v -f .azure-pipelines/vstest-exclude && exit 0
      git diff $tar_branch --name-only | grep -f .azure-pipelines/vstest-include && exit 0
      set +x
      echo "Skip vstest jobs"
      echo "##vso[task.setvariable variable=SKIP_VSTEST;isOutput=true]YES"
    name: SetVar
    displayName: "Set SKIP_VSTST variable"
