parameters:
- name: platforms
  type: object
  default:
  - vs
  - barefoot
  - broadcom
  - mellanox
  - centec-arm64
  - centec
  - nephos
  - innovium
  - marvell-armhf
  - generic

jobs:
- job: Build
  pool: sonicbld
  timeoutInMinutes: 120
  steps:
  - checkout: self
    clean: true
  - ${{ each platform in parameters.platforms }}:
    - task: DownloadPipelineArtifact@2
      displayName: Download ${{ platform }} versions-docker
      continueOnError: true 
      inputs:
        source: specific
        project: build
        pipeline: Azure.sonic-buildimage.official.${{ platform }}
        runVersion: 'latestFromBranch'
        runBranch: '$(Build.SourceBranch)'
        path: download
        patterns: |
          **/target/versions/default/versions-docker
  - script: |
      set -ex
      docker login $URL -u $(USER) -p $(PASSWD)
      images=$(find download -name versions-docker | xargs -i cat {} | sort -u | grep -v "==$" | sed -e "s/amd64://" -e "s/arm64://" -e "s/armhf://" -e "s/==/@/")
      for i in $images
      do
        docker pull $i
        image_tag=$(echo $i | awk -F@ '{print$1}')
        docker tag $i $URL/$image_tag
        docker push $URL/$image_tag
      done
    env:
      URL: $(url)
      USER: $(user)
      PASSWD: $(passwd)