parameters:
- name: pipelines
  type: object
  default:
  - 138
  - 139
  - 140
  - 141
  - 142
  - 143
  - 146
  - 147
  - 148
  - 149

jobs:
- job: Build
  pool: sonicbld
  timeoutInMinutes: 120
  steps:
  - checkout: self
    clean: true
  - script: mkdir download
  - ${{ each pipe in parameters.pipelines }}:
    - task: DownloadPipelineArtifact@2
      displayName: Download ${{ pipe }} versions-docker
      continueOnError: true 
      inputs:
        source: specific
        project: build
        pipeline: ${{ pipe }}
        runVersion: 'latestFromBranch'
        runBranch: '$(Build.SourceBranch)'
        path: (Build.SourcesDirectory)/download
        patterns: |
          **/target/versions/default/versions-docker
  - script: |
      set -ex
      ls -al
      find download