name: Build sonic-vs.img

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'branch name'
        required: true
        default: 'tests/vs-t0'
        type: string
  push:
    branches: [ tests/vs-t0 ]

jobs:
  build:

    runs-on: [self-hosted, jammy, x64, xlarge]

    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch_name }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Verify Python version
      run: python --version

    - name: install j2cli
      run: |
        pip3 install --user j2cli
        pip3 install --user j2cli --break-system-packages
        pip3 install --user jinjanator --break-system-packages

    - name: Run make init
      run: make init

    - name: Run make configure
      run: make configure PLATFORM=vs 
      
    - name: Run make all
      run: make target/sonic-vs.img.gz
