name: Build SONiC target

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'branch name'
        required: true
        default: 'tests/vs-t0'
        type: string
  push:
    branches: [ tests/vs-t0 ]

jobs:
  testflinger-build:
    runs-on: [self-hosted, testflinger]
    strategy:
      matrix:
        platform: [vs, broadcom]
    steps:
      - uses: actions/checkout@v4

      - name: Install Jinja2 CLI
        run: pip install jinja2

      - name: Check current directory
        run: pwd && ls -al

      - name: Generate job YAML
        id: create-job
        run: |
          export BRANCH=${{ github.head_ref || github.ref_name }}
          export PLATFORM=${{ matrix.platform }}
          export OUTPUT_PATH=build_${{ matrix.platform }}.yaml
          python3 ${{ github.workspace }}/.github/testflinger/generate.py
          echo "job-path=$OUTPUT_PATH" >> $GITHUB_OUTPUT

      - name: Check real job yaml
        run: echo "yaml file path=" ${{ steps.create-job.outputs.job-path }}

      - name: Submit job
        id: submit-job
        uses: canonical/testflinger/.github/actions/submit@main
        with:
          # poll: true
          job-path: ${{ steps.create-job.outputs.job-path }}

      - name: Display results
        id: get-results
        run: |
          testflinger results ${{ steps.submit-job.outputs.id }} > results.json

      - name: Check test status
        run: |
          status=$(jq '.test_status' results.json)
          if [ "$status" -ne 0 ]; then
            echo "testflinger task failed with status $status"
            jq -r '.test_output' results.json
            exit 1
          else
            echo "testflinger task succeeded"
          fi
