name: make vs

on:
  workflow_dispatch:
     inputs:
       branch_name:
          description: 'branch name'
          required: true
          default: 'master'
          type: string
          
jobs:
  build:

    runs-on: [self-hosted, jammy, x64, xlarge]

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch_name }}
        
    - name: Install dependencies
      run: sudo apt install -y python3-pip

    - name: install j2cli
      run: pip3 install --user j2cli

    - name: Run make init
      run: make init

    - name: Run make configure
      run: make configure PLATFORM=vs 
      
    - name: Run make all
      run: make  all
      
