# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

schedules:
- cron: "5 0 * * *"
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true

stages:
- stage: Build
  pool: sonicbld

  template: buildjob.yaml